# basic options
title: Personal Website
author: Thomas Kirsh
email: tkirsh2@illinois.edu
description: A wonderful site
# twitter_username: jekyllrb
github_username:  tk27182

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
